### ISSUE TITLE
setInitPosition not working properly

### ISSUE THREAD

**Issue by MhtSuthar** [brucetoo/PickView#12]
Hello, 
After successfully set list and setInitPosition properly, but some time i want to show different item position on loopview, than how to do it, i am trying to setInitPosition after button click but cant find solutions i dont know how to do it !

If you know than, how to clear past data on loopview and update new data?

**Comment by brucetoo** [comment]
There are no ways to  set position after init right now

**Comment by brucetoo** [comment]
use version 1.2.0
