### ISSUE TITLE
Cannot Resolve Symbol R on adding `compile 'com.brucetoo.pickview:library:1.1.1'`.

### ISSUE THREAD

**Issue by bshikhar13** [brucetoo/PickView#14]
I added compile 'com.brucetoo.pickview:library:1.1.1' in my build file and when synced, the symbol R (Resources one) became undefined.

**Comment by brucetoo** [comment]
Change this your project root build.gradle file like 
```groovy
allprojects {
    repositories {
        mavenCentral()
        jcenter()  //Must specify jcenter
    }
}
```

**Comment by bshikhar13** [comment]
I have already done it
