### ISSUE TITLE
你好，DatePickerPopWin显示的时候， 可以 通过api来定义显示动画的时间吗，还有显示的时候感觉会卡顿一下。

### ISSUE THREAD

**Issue by WongLu** [brucetoo/PickView#18]

**Comment by brucetoo** [comment]
显示的时间可以控制 但是没有加到Builder参数配置里面...你可以加一下.

**Comment by WongLu** [comment]
好的，谢谢。

**Comment by wl386123298** [comment]
卡顿貌似不是时间显示的问题。是由于在主线程做了太多的耗时操作！
I/Choreographer: Skipped 51 frames!  The application may be doing too much work on its main thread.

**Comment by brucetoo** [comment]
好的
