### ISSUE TITLE
how could I just show only two selection

### ISSUE THREAD

**Issue by MarnonLee** [brucetoo/PickView#19]
我怎么才能只显示两个选项呢？
` OptionsPickerView pvGenderOption = new OptionsPickerView(mContext);   
 ArrayList<String> genderStr = new ArrayList<>();      
 genderStr.add("male");       
genderStr.add("female");      
 pvGenderOption.setCyclic(false, true, true);       
 pvGenderOption.setPicker(genderStr);       
 pvGenderOption.setSelectOptions(1);        
pvGenderOption.setOnoptionsSelectListener((options1, option2, options3) -> {          
 String s = genderStr.get(options1);          
  mTvGender.setText(s);       
 });  
 pvGenderOption.show();`
![image](https://cloud.githubusercontent.com/assets/14787921/14973312/a8de11c4-1118-11e6-8ecb-007ca3c45b97.png)

**Comment by brucetoo** [comment]
You should see source code first(How three selection works),then you can see how to show two selection.
