### ISSUE TITLE
如何使LoopView恢复到初始位置

### ISSUE THREAD

**Issue by Freshman111** [brucetoo/PickView#22]
你好，我第一次使用PopupWindow弹出一个LoopView将它滑动到位置3，然后我并没有销毁这个PopupWindow，而是让它隐藏，然后我再次弹出这个PopupWindow，这时直接让它显示出来了。这时候LoopView的位置还是3，如何让它弹出时默认选中到第一个
我尝试使用下面的代码：
loopviewTime.setInitPosition(0);
loopviewTime.invalidate();
但是好像没有起到效果，能否指点下该如何做

**Comment by brucetoo** [comment]
今晚我看下

**Comment by brucetoo** [comment]
用分支[reconstuct]( https://github.com/brucetoo/PickView/tree/reconstuct) 的代码在试试

**Comment by Freshman111** [comment]
好的，非常谢谢

**Comment by brucetoo** [comment]
最近有点忙,过段时间我把代码重构下

**Comment by Freshman111** [comment]
我试了下好像还是不行。我是调用的这个方法loopviewTime.setInitPosition(0);来设置每次弹出开始选中第一个。
我在setInitPosition方法里改了一句代码如下，好像可以了。但是没有仔细看不知道这样做会不会有其它的副作用
 public final void setInitPosition(int initPosition) {
        this.initPosition = initPosition;
        totalScrollY=0;
        invalidate();
    }

**Comment by brucetoo** [comment]
等我过两天重构，这里代码好多问题 之前一直没自己看过实现代码

**Comment by brucetoo** [comment]
用最新代码
