### ISSUE TITLE
Crash on new update

### ISSUE THREAD

**Issue by khachlangthang** [brucetoo/PickView#25]
Hello,
I have spent 4 hours for an issue when use this library with Android studio.
It was updated on 2016-07-09, that make LoopView constructor direct call to   @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    public LoopView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {...}
All my devices below android 5.0 are crash, with exception about inflate layout.
You can use 1.1.1 to avoid this problem or wait a new update.

**Comment by brucetoo** [comment]
fix it in ```compile 'com.brucetoo.pickview:library:1.2.1' ```
