### ISSUE TITLE
切换不同的list

### ISSUE THREAD

**Issue by jituijiaqiezi** [brucetoo/PickView#27]
我要通过切换分钟、小时、天等选项，使用loopView保存每个滑动的list，最后会错乱，可以清除loopView的数据吗

**Comment by brucetoo** [comment]
重新设置dataList 不可以?

**Comment by jituijiaqiezi** [comment]
@brucetoo 可以重置list，但是保存的滑动位置不对，初始化滑动位置使用initPosition吧

**Comment by brucetoo** [comment]
初始化滑动位置是用initPosition啊
