### ISSUE TITLE
作者省市区  选择的  间距怎么调整，现在好大

### ISSUE THREAD

**Issue by gaaraWB** [brucetoo/PickView#3]
您好，现在我想做 省市区的选择，用loopview 修改总是 角标越界，用您提供的pickview  样式怎么调整间距那？  为什么loopview和pickview不用一套算法算布局那？

**Comment by gaaraWB** [comment]
现在是好小。。。

**Comment by brucetoo** [comment]
pickview 只是一个 popwindow而已 ，你完全可以就在现有的基础上将年月日缓成省市区
