### ISSUE TITLE
in version 1.2.1 custom not applied

### ISSUE THREAD

**Issue by derohimat** [brucetoo/PickView#30]
Confirm and Cancel Button not showing in Marshmallow but can  clicked.
![device-2016-09-02-164146](https://cloud.githubusercontent.com/assets/3787041/18199815/41ce2928-712c-11e6-94e1-e15f523c85ea.png)

**Comment by brucetoo** [comment]
Can you offer more information,i works well in Marshmallow of mine.

**Comment by brucetoo** [comment]
fixed in version `com.brucetoo.pickview:library:1.2.2`
