### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by k525245669** [brucetoo/PickView#31]
when i set the app:drawItemCount to more then 7,  then the centerText  will  in incorrect position.I'm trying to fix this bug, if i fixed ,can you merge my code?

**Comment by brucetoo** [comment]
PR is so welcome..and i will check it.

**Comment by brucetoo** [comment]
`drawItemCount` must be odd number and please check out if the `initPosition` is what you set.
" the centerText will in incorrect position " it seems cause by your `initPosition` params

**Comment by k525245669** [comment]
thanks, i found it cause by drawItemCount, because i set it to 10. How about to check the mDrawItemCount in the initView(Context context, AttributeSet attrs) like:  if(mDrawItemsCount%2==0) mDrawItemsCount++;  thanks for this bug,  it drive me to read your code carefully, the code in onDraw is so cool, Thanks

**Comment by brucetoo** [comment]
before you use this lib.it's better to read [README.md](https://github.com/brucetoo/PickView/blob/master/README.md) first.
