### ISSUE TITLE
have any better way to calculate the  mMaxTextHeight 

### ISSUE THREAD

**Issue by k525245669** [brucetoo/PickView#32]
if i have 2 pickView, one is used for display Chinese year like "2016年"，another is used for display the Chinese Month like "9月"， i need two pickView's TopLine   to keep in one line,but the  two pickView 's mMaxTextHeight is diff,because of "年" and "月" 's Height is diff.So,the mTopLineY, and mBottomLineY will be diff in the two pickView. have any advice for me?

**Comment by brucetoo** [comment]
You can put '年','月'  inside two TextView between your two PickView.and the problems is gone.

**Comment by k525245669** [comment]
sorry, i use the LoopView ,not PickView.
      this is my solution:
       
        //draw top and bottom line
        int halfItemHight =  Math.round(getmItemHeight()/50) * 25 ; //cut the diff height count
        int fixTopLineY = getHeight()/2 - halfItemHight;
        int fixBottomLineY = getHeight()/2 + halfItemHight;

        canvas.drawLine(0.0F, fixTopLineY, mWidgetWidth, fixTopLineY, mCenterLinePaint);
        canvas.drawLine(0.0F, fixBottomLineY, mWidgetWidth, fixBottomLineY, mCenterLinePaint);

**Comment by 2410911490** [comment]
should modify method measureTextWidthHeight
use FontMetrics measure textHeight

//measure max textHeight 
`Paint.FontMetrics fontMetrics = mCenterTextPaint.getFontMetrics();`
 //measure max textHeight
`int textHeight = (int) (fontMetrics.bottom - fontMetrics.top);`
`if (textHeight > mMaxTextHeight) {
                mMaxTextHeight = textHeight;
            }`

**Comment by brucetoo** [comment]
I think @2410911490 had never tried why you suggest. And that not work well.

**Comment by 2410911490** [comment]
there are 3 loopview in linearlayout(horizontal), "xx月xx日","xx点",'xx分',their topLine not keep in one line,
like "------_____",if i change measureTextWidthHeight method ,it will ok. so, i think "textHeight " is diff.
thanks

**Comment by brucetoo** [comment]
Humm...Thanks for your suggestion.I.will figure it out

**Comment by brucetoo** [comment]
I just check this carefully, @2410911490 through what you mention can keep the same height in different LoopView(This will cause a bigger height than what i think). But i think if there are more than one LoopView, and we just need a OPTION(keep the same height of different LoopView).Calculate the different data string in different LoopView, find the max one, and we setup for every LoopView Or do as i mention in second comment

**Comment by k525245669** [comment]
@brucetoo @2410911490 thanks for your helps

**Comment by abdulrehmank7** [comment]
Checkout this
 https://arkapp.medium.com/ios-date-time-picker-for-android-93af45fdfaf0
