### ISSUE TITLE
PickView is not working in Android 3.0 

### ISSUE THREAD

**Issue by umerabidin** [brucetoo/PickView#53]
Hy, 
I am Muhammad Umer and i am using pickview in my android studio version 3.0 
but when I sync my project it show style.xml file error.
When I comment this library and sync it works fine but with this it shows error and it is shown in this attached screenshot.
Any one please help me to sort it out.

![cats](https://user-images.githubusercontent.com/9766668/32068081-abbca8fc-ba9e-11e7-86dd-a7abd779b996.jpg)

**Comment by brucetoo** [comment]
it's not the problem of PickView . please post this in [Stackoverflow](https://stackoverflow.com/),but add this(`android.enableAapt2=false`) in root grade file may help.
