### ISSUE TITLE
你好，通过gradle将PickView引入到项目中，DatePickerPopWin选择日期的时候，怎么改变"cancel"和"confirm" 这个两个Button的text?

### ISSUE THREAD

**Issue by WongLu** [brucetoo/PickView#6]

**Comment by brucetoo** [comment]
额。。这个我后面加上些attr吧  现在你可以直接用源码自己改，暂时我还加自定义 text,颜色什么的...

**Comment by WongLu** [comment]
很好用的控件，辛苦啦！

**Comment by brucetoo** [comment]
恩,改天我加上些自定义的样式属性，早就想加了 可惜有点懒.

**Comment by brucetoo** [comment]
已经加上自定义的一些属性 [Version 1.1.1](https://github.com/brucetoo/PickView/commit/13f193db8c14ba56252838e4e9e61d2c056a97cd)

**Comment by WongLu** [comment]
太赞了!
