### ISSUE TITLE
How to set all text to center align

### ISSUE THREAD

**Issue by MhtSuthar** [brucetoo/PickView#8]
This is my app screen shots, i am using your lib, bt i cant find how to center align text, plz help anything.

![untitled](https://cloud.githubusercontent.com/assets/7448975/12235001/bd8ee93e-b896-11e5-8c4c-10e04be42d25.png)

**Comment by brucetoo** [comment]
May have a problem in method onDraw,please show me your layout xml.

**Comment by MhtSuthar** [comment]
Thanx for your reply, i solve my problem

i set 
paintB.setTextAlign(Paint.Align.CENTER);

and on draw
int left = measuredWidth /2 ;

**Comment by brucetoo** [comment]
please try code in branch [reconstuct](https://github.com/brucetoo/PickView/tree/reconstuct)

**Comment by brucetoo** [comment]
use version 1.2.0 instead
