### ISSUE TITLE
Not able to return current year if i set max year before min year.

### ISSUE THREAD

**Issue by raviteja06** [brucetoo/PickView#9]
.dateChose(calendar.get(Calendar.YEAR) + "-" +
                            (calendar.get(Calendar.MONTH) + 1) + "-" +
                            calendar.get(Calendar.DATE)) // date chose when init popwindow
.maxYear(2099)
.minYear(1900)
.build();

**Comment by brucetoo** [comment]
it's your dataChose giving wrong data,not the problem of you said  "set max year before min year"
